//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolutionRunner.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SolutionRunner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 36743676522426214741687639282183216978128565594112364817283598621384839756628424146779311928318383597235968644687665159591573413233616717112157752469191845757712928347624726438516211153946892241449523148419426259291788938621886334734497823163281389389853675932246734153563861233894952657625868415432316155487242813798425779743561987563734944962846865263722712768674838244444385768568489842989878163655771847362656153372265945464128668412439248966939398765446171855144544285463517258749813731314365947372548811434 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InputDay01 {
            get {
                return ResourceManager.GetString("InputDay01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 278	1689	250	1512	1792	1974	175	1639	235	1635	1690	1947	810	224	928	859
        ///160	50	55	81	68	130	145	21	211	136	119	78	174	155	149	72
        ///4284	185	4499	273	4750	4620	4779	4669	2333	231	416	1603	197	922	5149	2993
        ///120	124	104	1015	1467	110	299	320	1516	137	1473	132	1229	1329	1430	392
        ///257	234	3409	2914	2993	3291	368	284	259	3445	245	1400	3276	339	2207	233
        ///1259	78	811	99	2295	1628	3264	2616	116	3069	2622	1696	1457	1532	268	82
        ///868	619	139	522	168	872	176	160	1010	200	974	1008	1139	552	510	1083
        ///1982	224	3003	234	21 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InputDay02 {
            get {
                return ResourceManager.GetString("InputDay02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 265149.
        /// </summary>
        internal static string InputDay03 {
            get {
                return ResourceManager.GetString("InputDay03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sayndz zfxlkl attjtww cti sokkmty brx fhh suelqbp
        ///xmuf znkhaes pggrlp zia znkhaes znkhaes
        ///nti rxr bogebb zdwrin
        ///sryookh unrudn zrkz jxhrdo gctlyz
        ///bssqn wbmdc rigc zketu ketichh enkixg bmdwc stnsdf jnz mqovwg ixgken
        ///flawt cpott xth ucwgg xce jcubx wvl qsysa nlg
        ///qovcqn zxcz vojsno nqoqvc hnf gqewlkd uevax vuna fxjkbll vfge
        ///qrzf phwuf ligf xgen vkig elptd njdm gvqiu epfzsvk urbltg dqg
        ///sfpku viwihi fje umdkwvi ejzhzj qrbl sfpku sad nawnow ksnku
        ///nzhj mfudick ueaa jnhz kpy pzk
        ///euiin xvl elaoelu wbdd xlv [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InputDay04 {
            get {
                return ResourceManager.GetString("InputDay04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1
        ///1
        ///0
        ///-1
        ///-3
        ///0
        ///-5
        ///-1
        ///2
        ///0
        ///-1
        ///-3
        ///-9
        ///-5
        ///-1
        ///-9
        ///2
        ///2
        ///-13
        ///-7
        ///-13
        ///-18
        ///0
        ///0
        ///-21
        ///-10
        ///-2
        ///-12
        ///-18
        ///-4
        ///-27
        ///-24
        ///-16
        ///-10
        ///-24
        ///-12
        ///-5
        ///-31
        ///-17
        ///-10
        ///-22
        ///-16
        ///-3
        ///-10
        ///-5
        ///-37
        ///-16
        ///-4
        ///-8
        ///-1
        ///-44
        ///-12
        ///-38
        ///-42
        ///-27
        ///-9
        ///-52
        ///-13
        ///-12
        ///-36
        ///-26
        ///2
        ///-48
        ///-2
        ///-3
        ///-17
        ///1
        ///-51
        ///-47
        ///-68
        ///-42
        ///0
        ///-53
        ///-47
        ///-34
        ///-17
        ///-15
        ///-10
        ///-76
        ///-53
        ///-58
        ///-24
        ///-62
        ///-78
        ///-11
        ///-5
        ///-71
        ///-52
        ///-41
        ///-84
        ///-57
        ///-63
        ///-88
        ///-11
        ///-61
        ///-55
        ///-85
        ///-61
        ///-87
        ///-57
        ///-46
        ///-94
        ///-19
        ///-31
        ///-84
        ///-60
        ///-7
        ///-31
        ///-25
        ///-90
        ///-108
        ///-79
        ///- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InputDay05 {
            get {
                return ResourceManager.GetString("InputDay05", resourceCulture);
            }
        }
    }
}
